name: tinikling
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  fluttertoast: ^8.2.8
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  image_path: "assets/icon_logo.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon_logo.png
    - assets/kimono.jpeg
    - assets/kimono2.jpeg
    - assets/barong.jpeg
    - assets/buwan.jpeg
    - assets/Waltz.mp4
